### ISSUE TITLE
Memory pipeline

### ISSUE THREAD

**Issue by Sustrak** [Sustrak/Segre#23]
The processor will implement instructions caches ($I), data caches ($D) and virtual memory.

### Instruction Cache ($I)
Cache memory from where the processor will fetch new instructions. It has the following characteristics:
| Spec      | Decision     |
|:-----------:|:---------------:|
|    Hit       | No penalty |
|    Miss    | 10 cycle penalty (5 cycle to access memory + 5 cycle to memory answer back) |
|   # lines  | 4                |
|  Line size | 16 bytes   |
| Replacement | LRU |
| Associativity   | 1 |
|Write policy| -----|

### Data Cache ($D)
Cache memory from where the processor will fetch the data. It has the following characteristics:
| Spec      | Decision     |
|:-----------:|:---------------:|
|    Hit       | No penalty |
|    Miss    | 10 cycle penalty (5 cycle to access memory + 5 cycle to memory answer back) |
|   # lines  | 4                |
|  Line size | 16 bytes   |
| Replacement | LRU |
| Associativity   | 1 |
|Write policy| Write through|

To support stores, without changing the pipeline, a **Store Buffer (SB)** will be added to the microarchitecture. It will have the following characteristics:
| Spec      | Decision     |
|:-----------:|:---------------:|
| # Entries | 2 |
| Entry size | 64bits (32@ + 32 data)|

It will use the MEM stage of ALU operations to empty one element of the buffer.

#### Pipeline stalls
| Situation      | Stall     |
|:-----------:|:---------------:|
| Load hit | No |
| Load miss | Yes |
| Write hit | No|
| Write miss | No |

### Virtual Memory
In order to implement virtual memory one more stage will be added to the pipeline the TLB + Lookup (TL) stage. 
#### TLB + Lookup (TL) stage
It will be responsible for translating the virtual address to the corresponding physical one and check if the tag resulting form the physical address is located in the data cache.

**Comment by Sustrak** [comment]
- **Store miss**: When Segre performs a store and the tag data cache produce a miss, Segre will issue a request for the cache line and send the data to the main memory at the same time. As long as the store buffer has enough space to store the data the execution won't stall.

In order to make the architecture easier the write through will be performed when the data is stored in the store buffer.

To support this feature we need to let know the TL stage that a request to the mmu will be on-flight for the new memop operations so it can stall the pipeline if:
- A new store arrives and don't have the same tag as the first faulty one
- A new load arrives: In this case we won't issue a new request if the load has the same tag as the faulty store.

Another thing to take into account is that the StoreBuffer won't be able to write the data if the line is not present in the cache. The StoreBuffer will write when the data tag cache outputs a hit, and it will do it into the index the data tag cache says.

One more thing is that when replacing a cache line we need to make sure that there are not pending requests in the StoreBuffer that goes into that line. If so we will invalidate that requests in the StoreBuffer.

**Comment by Jooooc** [comment]
Issue: For some reason, in the "st_ld_w" test at 14900 ns, the data coming from memory is written into position 3 of cache and not at 0. During the whole execution, the LRU mechanism never selects the position 0 to write the data. Although it doesn't generate an incorrect result, it may cause some performance issues.
