### ISSUE TITLE
ADD, SUB, SLL, SLT, SLTU, XOR, SRL, SRA, OR, AND

### ISSUE THREAD

**Issue by Sustrak** [Sustrak/Segre#3]
Check that the tests:
ADD, SUB, SLL, SLT, SLTU, XOR, SRL, SRA, OR, AND

works and completes well. Else fix the issues related

**Comment by Marc43** [comment]
By the moment I would say they work. The only problem is with the "false" mismatches #11

**Comment by Sustrak** [comment]
cheked with 1c30b6a175e1032a14d4223043971824f139c9b2 and it only fails in `srl` and `sra`
